spring.application.name=ambulance

spring.datasource.url=jdbc:postgresql://localhost:5432/city_ambulance
spring.datasource.username=postgres
spring.datasource.password=Bhushan3377@postgres

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

ambulance.default.password=defaultPassword123

password.encryption.enabled=true

# Configure a dummy issuer URI for JWT decoding during development.
# In a production environment, this should point to your actual OAuth2 Authorization Server's issuer URI.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080